### ISSUE TITLE
Error on training on scanobjectNN dataset

### ISSUE THREAD

**Issue by libeike** [princeton-vl/SimpleView#11]
‘’‘
--2022-07-12 03:24:51--  https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Issued certificate has expired.
To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.
unzip:  cannot find or open modelnet40_ply_hdf5_2048.zip, modelnet40_ply_hdf5_2048.zip.zip or modelnet40_ply_hdf5_2048.zip.ZIP.
mv: cannot stat 'modelnet40_ply_hdf5_2048': No such file or directory
rm: cannot remove 'modelnet40_ply_hdf5_2048.zip': No such file or directory
(('dataset', 'object'), ('views', 6), ('resolution', 128), ('trans', -1.4), ('size', 4), ('normalize', False), ('norm_pc', True))
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    ('norm_pc', NORMALIZED),
  File "/content/drive/MyDrive/SimpleView-master/ScanObjectNN/SimpleView/utils/utils.py", line 93, in get_mv_mean_var
    mean_var_list = data[param_tuple]
KeyError: (('dataset', 'object'), ('views', 6), ('resolution', 128), ('trans', -1.4), ('size', 4), ('normalize', False), ('norm_pc', True))
‘’‘

**Comment by boweiliu0428** [comment]
This an error caused by downloading modelnet40. As the error suggests, have you tried adding `--no-check-certificate' to the download command?

**Comment by libeike** [comment]
I downloaded the modelnet40 dataset using 
!wget --no-check-certificate https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip


But it still suggests
To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.

--2022-07-12 06:19:03--  https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Issued certificate has expired.
To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.
Archive:  modelnet40_ply_hdf5_2048.zip
   creating: modelnet40_ply_hdf5_2048/
  inflating: modelnet40_ply_hdf5_2048/ply_data_train_2_id2file.json  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train2.h5  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train4.h5  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train1.h5  
  inflating: modelnet40_ply_hdf5_2048/train_files.txt  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train_4_id2file.json  
  inflating: modelnet40_ply_hdf5_2048/ply_data_test1.h5  
  inflating: modelnet40_ply_hdf5_2048/ply_data_test0.h5  
  inflating: modelnet40_ply_hdf5_2048/ply_data_test_1_id2file.json  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train_1_id2file.json  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train_0_id2file.json  
  inflating: modelnet40_ply_hdf5_2048/test_files.txt  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train0.h5  
  inflating: modelnet40_ply_hdf5_2048/ply_data_test_0_id2file.json  
  inflating: modelnet40_ply_hdf5_2048/shape_names.txt  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train3.h5  
  inflating: modelnet40_ply_hdf5_2048/ply_data_train_3_id2file.json  
(('dataset', 'object'), ('views', 6), ('resolution', 128), ('trans', -1.4), ('size', 4), ('normalize', False), ('norm_pc', True))
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    ('norm_pc', NORMALIZED),
  File "/content/drive/MyDrive/SimpleView-master/ScanObjectNN/SimpleView/utils/utils.py", line 93, in get_mv_mean_var
    mean_var_list = data[param_tuple]
KeyError: (('dataset', 'object'), ('views', 6), ('resolution', 128), ('trans', -1.4), ('size', 4), ('normalize', False), ('norm_pc', True))

Unpacking the modelnet40 zip was successful, but I still get this result, can you help me find the problem?

**Comment by libeike** [comment]
> This an error caused by downloading modelnet40. As the error suggests, have you tried adding `--no-check-certificate' to the download command?

I downloaded the modelnet40 dataset using
`!wget --no-check-certificate https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip`

But it still suggests
`To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.`

```
--2022-07-12 06:19:03-- https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
Issued certificate has expired.
To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.
Archive: modelnet40_ply_hdf5_2048.zip
creating: modelnet40_ply_hdf5_2048/
inflating: modelnet40_ply_hdf5_2048/ply_data_train_2_id2file.json
inflating: modelnet40_ply_hdf5_2048/ply_data_train2.h5
inflating: modelnet40_ply_hdf5_2048/ply_data_train4.h5
inflating: modelnet40_ply_hdf5_2048/ply_data_train1.h5
inflating: modelnet40_ply_hdf5_2048/train_files.txt
inflating: modelnet40_ply_hdf5_2048/ply_data_train_4_id2file.json
inflating: modelnet40_ply_hdf5_2048/ply_data_test1.h5
inflating: modelnet40_ply_hdf5_2048/ply_data_test0.h5
inflating: modelnet40_ply_hdf5_2048/ply_data_test_1_id2file.json
inflating: modelnet40_ply_hdf5_2048/ply_data_train_1_id2file.json
inflating: modelnet40_ply_hdf5_2048/ply_data_train_0_id2file.json
inflating: modelnet40_ply_hdf5_2048/test_files.txt
inflating: modelnet40_ply_hdf5_2048/ply_data_train0.h5
inflating: modelnet40_ply_hdf5_2048/ply_data_test_0_id2file.json
inflating: modelnet40_ply_hdf5_2048/shape_names.txt
inflating: modelnet40_ply_hdf5_2048/ply_data_train3.h5
inflating: modelnet40_ply_hdf5_2048/ply_data_train_3_id2file.json
(('dataset', 'object'), ('views', 6), ('resolution', 128), ('trans', -1.4), ('size', 4), ('normalize', False), ('norm_pc', True))
Traceback (most recent call last):
File "train.py", line 141, in
('norm_pc', NORMALIZED),
File "/content/drive/MyDrive/SimpleView-master/ScanObjectNN/SimpleView/utils/utils.py", line 93, in get_mv_mean_var
mean_var_list = data[param_tuple]
KeyError: (('dataset', 'object'), ('views', 6), ('resolution', 128), ('trans', -1.4), ('size', 4), ('normalize', False), ('norm_pc', True))
```

Unpacking the modelnet40 zip was successful, but I still get this result, can you help me find the problem?

**Comment by boweiliu0428** [comment]
If you have downloaded and unziped the file, then you should comment out the code that downloads and unzips. The current error looks like it is trying to download and unzip again. 

Please provide the full code you are running if you still encounter problems.

**Comment by libeike** [comment]
I had found my error:

I ran the `train.py` directly without using the parameters in the `scripts/train_scanobjnn.sh`

I am very sorry to have wasted your time and thank you for your help!

**Comment by libeike** [comment]
> If you have downloaded and unziped the file, then you should comment out the code that downloads and unzips. The current error looks like it is trying to download and unzip again.
> 
> Please provide the full code you are running if you still encounter problems.

Sorry to bother you again, but if I want to get a depth image of each data of the scanobjectNN dataset, how do I save it in a separate file.

**Comment by libeike** [comment]
> My apologies for creating this issue. I used matplotlib for visualization and it shows the view correctly.

Hi,

I used matplotlib to get the correct image and to get the desired multi-views image for my own needs. Thanks again for your help.

**Comment by libeike** [comment]
> If you have downloaded and unziped the file, then you should comment out the code that downloads and unzips. The current error looks like it is trying to download and unzip again.
> 
> Please provide the full code you are running if you still encounter problems.

I had changed
https://github.com/princeton-vl/SimpleView/blob/0612474b043f4cafd1f69531c44bb6a6600b6d31/ScanObjectNN/SimpleView/train.py#L122
to
`SHUFFLE =FLAGS.no_shuffle #SHUFFLE =True`

why I print `current_label` in
https://github.com/princeton-vl/SimpleView/blob/0612474b043f4cafd1f69531c44bb6a6600b6d31/ScanObjectNN/SimpleView/train.py#L528
and
https://github.com/princeton-vl/SimpleView/blob/0612474b043f4cafd1f69531c44bb6a6600b6d31/ScanObjectNN/SimpleView/train.py#L603
still gives a disrupted result similar to the following：
[14  3  5 ...  3 12  7]
[7 1 1 ... 2 4 0]

**Comment by imankgoyal** [comment]
Hi,

Apologies for the delayed response. The line you mentioned is the point-cloud data. I would suggest you can get the images from this line: https://github.com/princeton-vl/SimpleView/blob/master/ScanObjectNN/SimpleView/train.py#L556.

You might need to disable any data augmentation, or potentially write a separate script to just save all the images following the code in training_one_epoch.

Hope it helps.

Best,
Ankit

**Comment by libeike** [comment]
I found out that it was data_utils.get_current_data_h5 that was messing with the data, just skip this and reassign it.

Thank you for your continued help.

https://github.com/princeton-vl/SimpleView/blob/0612474b043f4cafd1f69531c44bb6a6600b6d31/ScanObjectNN/SimpleView/train.py#L528
