### ISSUE TITLE
Cannot download the modelnet40 val split

### ISSUE THREAD

**Issue by auniquesun** [princeton-vl/SimpleView#15]
As a researcher from China, I cannot download the modelnet40 validataion split as I cannot acess google in Linux command line.

Could you please provide a download link of the modelnet40 validation split that is open from the browser? I can acess google from the browser.

Thanks.

**Comment by boweiliu0428** [comment]
https://docs.google.com/uc?export=download&id=1SHAnRFKj6wuwdSgB_B1Kzw32_gEkqADN
