### ISSUE TITLE
Multi-GPU Support

### ISSUE THREAD

**Issue by sheshap** [princeton-vl/SimpleView#3]
Thank you so much for releasing the code.

I noticed the below error when I tried to training using 2 GPUs.

RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:540

Please let us know if the code supports multi-GPU training?

**Comment by imankgoyal** [comment]
Hello,

Thanks foy your interest in our work. The multi-gpu training should work for PointNet++, PointNet, DGCNN. We have not tested it for RSCNN and SimpleView. Please share the exact command and config you were using.

Thanks,
Ankit

**Comment by sheshap** [comment]
Hi Ankit,

I am using below command.
python main.py --exp-config configs/dgcnn_simpleview_ce_run_1.yaml

The error at the last but 2 lines in file mv_utils.py

        points = torch.matmul(points, rot_mat)
        points = points - translation

If I comment these lines it works perfectly fine.

Thanks
Shivanand

**Comment by imankgoyal** [comment]
I checked the code. It looks like the current code does not support multi-gpu training for SimpleView. I edited my earlier comment. Please pull the commit (https://github.com/princeton-vl/SimpleView/commit/0612474b043f4cafd1f69531c44bb6a6600b6d31) and it should work.

**Comment by sheshap** [comment]
Thank you. It worked.
