### ISSUE TITLE
code for cross-dataset training

### ISSUE THREAD

**Issue by sheshap** [princeton-vl/SimpleView#6]
Hi Team,

Can you please post commands/scripts used for cross-dataset training? 
To reproduce Table 5 results (col 3 and col 4).

Thanks in advance.

**Comment by imankgoyal** [comment]
Hi,

Those scripts are here: https://github.com/princeton-vl/SimpleView/tree/master/ScanObjectNN/SimpleView

Best,
Ankit

**Comment by sheshap** [comment]
Hi Ankit,

Thanks for this link.
This has Pointnet++ (Tensorflow version). I am specifically looking forward to using your PyTorch code to train ScanObjectNN (similar to how you do for ModelNet40).

Under your main SimpleView folder, you have provided the Pytorch version of pointnet++ as well.

Did you try training ScanObjectNN using the PyTorch version?
Accuracies are quite high (PB_T50_RS gave 81.5% for SimpleView).

It would be of great help if you could share PyTorch scripts for cross-dataset experiments.

**Comment by imankgoyal** [comment]
Unfortunately we don’t have PyTorch version for ScanObjectNN. We use the official Tensorflow repo for it.
