### ISSUE TITLE
A question about '_ext.pointnet2._pointnet2'

### ISSUE THREAD

**Issue by liuhui0401** [princeton-vl/SimpleView#9]
I reported this error in pointnet2_pyt when I ran the code. How should I solve it? Also, the git link to the requirement.txt of pointnet2_pyt is dead.

**Comment by imankgoyal** [comment]
Hi, 

I was wondering if you tried following the instructins on the readme. These should install pointnet2_pyt.



![Screen Shot 2022-07-01 at 5 14 36 PM](https://user-images.githubusercontent.com/23709936/176968749-8c3a45b9-6f47-43b4-92dc-f86012de8dbc.png)

**Comment by liuhui0401** [comment]
> 

Yes, I have tried following the instructions on the readme. But I found the git link to the requirements.txt for PointNet2 is dead. I can't configure the environment successfully.

**Comment by liuhui0401** [comment]
Sorry I didn't describe my problem clearly. The error I encountered was "No module named '_ext.pointnet2._pointnet2'", and I did not find this file.

**Comment by imankgoyal** [comment]
I am not sure if I understand which git link you referring to.

If you mean the git link for `etw_pytorch_utils` here: https://github.com/princeton-vl/SimpleView/blob/master/pointnet2_pyt/requirements.txt#L1, i.e. inside the requirements.txt inside SimpleView/pointnet2_pyt then it is not required.

The correct version of `etw_pytorch_utils` repository is present as a fork and the link is present here: https://github.com/princeton-vl/SimpleView/blob/master/requirements.txt

If you first do `pip install -r requirements.txt` from the SimpleView folder, the correct reposity will automatically be installed.

In case you are running into some other problem, then it is very hard for me to help with the information you provided. It would be good if you can provide the log of each of the steps in the instructions.

**Comment by liuhui0401** [comment]
I have successfully configured the pointnet2 environment. I found that the previous error was due to the rscnn environment not being configured properly. Thank you very much!

**Comment by imankgoyal** [comment]
Great. Closing the issue.
